// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXv5u9Jcu0erasryGg5Ur9HWtiamST8DQ',
    appId: '1:749901460475:web:a1693c698bf03170b9915e',
    messagingSenderId: '749901460475',
    projectId: 'roteiro-do-vinho',
    authDomain: 'roteiro-do-vinho.firebaseapp.com',
    storageBucket: 'roteiro-do-vinho.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOWjbccwtnnqqkJ4QPveFHWweCQBgDTxU',
    appId: '1:749901460475:android:2844e9a4ee4955c4b9915e',
    messagingSenderId: '749901460475',
    projectId: 'roteiro-do-vinho',
    storageBucket: 'roteiro-do-vinho.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkYcuO9j3OzSOxdLrT9iot2icynzZauJg',
    appId: '1:749901460475:ios:aa02cfd093520f51b9915e',
    messagingSenderId: '749901460475',
    projectId: 'roteiro-do-vinho',
    storageBucket: 'roteiro-do-vinho.firebasestorage.app',
    iosClientId: '749901460475-pi6upvr37r7v5j8aipd06br296503j1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.roteirodovinho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkYcuO9j3OzSOxdLrT9iot2icynzZauJg',
    appId: '1:749901460475:ios:aa02cfd093520f51b9915e',
    messagingSenderId: '749901460475',
    projectId: 'roteiro-do-vinho',
    storageBucket: 'roteiro-do-vinho.firebasestorage.app',
    iosClientId: '749901460475-pi6upvr37r7v5j8aipd06br296503j1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.roteirodovinho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXv5u9Jcu0erasryGg5Ur9HWtiamST8DQ',
    appId: '1:749901460475:web:35c53a26267b15e3b9915e',
    messagingSenderId: '749901460475',
    projectId: 'roteiro-do-vinho',
    authDomain: 'roteiro-do-vinho.firebaseapp.com',
    storageBucket: 'roteiro-do-vinho.firebasestorage.app',
  );
}
